#!/bin/bash
export dateTime=`date +\%m\%d_\%H_\%M`
export scriptDir="${HOME}/Evolution2014/scripts"
export LocalServer="${HOME}/Desktop/Evo14LocalMirror/EvoPresentation"
export LocalServerCache="${LocalServer}/Cache"

if [ ! -d $LocalServerCache ]
  then mkdir -p $LocalServerCache;
fi

#export XCDFTPAddress="ftp://evo2014@184.175.78.150/"
export XCDFTPAddress="ftp://Evo2014@xcdsystem.com/"
. ${scriptDir}/exportMapping
