#!/bin/bash
export scriptDir="${HOME}/Evolution2014/scripts"
export LocalServer="${HOME}/Desktop/Evo14LocalMirror/EvoPresentation"
export LocalServerCache="${LocalServer}/Cache"

export XCDFTPAddress="ftp://evo2014@184.175.78.150/"
. ${scriptDir}/exportMapping
