#!/bin/bash
export scriptDir="/home/evo14/Evolution2014/scripts/"
export LocalServerCache="/home/evo14/Desktop/Evo14LocalMirror/EvoPresentation/Cache"
export LocalServer="/home/evo14/Desktop/Evo14LocalMirror/EvoPresentation"

export XCDFTPAddress="ftp://evo2014@184.175.78.150/"
. ${scriptDir}/exportMapping
