#!/bin/bash
#. ${scriptDir}/syncXCDToLocalMirror_wget
. ${scriptDir}/syncXCDToLocalMirror
. ${scriptDir}/syncProcessLocalCache
. ${scriptDir}/syncLocalMirrorToRoom
#. ${scriptDir}/syncLocalMirrorToRoom_sftp

