#!/bin/bash
##### Install crontab on primary materials server #####
# crontab serverCrontab; 
#######################################################
PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin"
Logfile=/Desktop/Evo14LocalMirror/Log/
#LogSubFile=/Desktop/Evo14LocalMirror/Log/f1
#*/30 * * * * /home/sw167/Evolution2014/scripts/variableList > /home/sw167/Desktop/Evo14LocalMirror/EvoPresentation/crontabLog 2>&1
#*/30 6-19 * * * ${Home}/Evolution2014/scripts/runAll > ${HOME}${Logfile}`date +\%m\%d_\%H_\%M` 2>&1
#5 0 * * * /home/sw167/Evolution2014/scripts/runAll > ${Logfile}`date +\%m\%d_\%H_\%M` 2>&1
#14 * * * * /home/sw167/Evolution2014/scripts/runSyncXCD > ${HOME}/Desktop/testsss2 2>&1
#17 * * * * ${HOME}/Evolution2014/scripts/runSyncXCD > ${HOME}/Desktop/testsss 2>&1
*/30 * * * * ${HOME}/Evolution2014/scripts/runSyncXCD > ${HOME}/${Logfile}"syncXCD_"`date +\%m\%d_\%H_\%M` 2>&1 


