#!/bin/bash
## don't think this works for mac hostname -I
ServerIP="192.168.1.199"
ServerIP="152.3.59.21"
serverRecord="/home/sw167/Desktop/Evo14LocalMirror/EvoPresentation/RoomInfo/"
Room=$1

tempFile="/Users/admin/${1}_info"

if [ -n "${1}" ]
  then 
  echo "Setup Room:${1}" >> ${tempFile}
else
  echo "Please provide room code!! Exit script"
  exit 6
fi
# One of these should work
#best
#ifconfig en0| grep 'inet ' | cut -d: -f2 | awk '{ print $2}'

#ifconfig | grep 'inet ' | cut -d: -f2 | awk '{ print $2}' > ${tempFile}
#ifconfig en0| grep 'inet ' | cut -d: -f2 | awk '{ print $2}'
#ifconfig | awk -F ":"  '/inet /{split($1,a," ");print a[2]}'
#ifconfig | awk -F ' *|:' '/inet /{print $2}'
#if not, go back to the old way

echo "IP: `ipconfig getifaddr en0`"
ipconfig getifaddr en0 >> $tempFile

#en1 for wireless

## send IP to server


## add pub key to authorized_keys
#cat `curl -sk3 -O https://raw.githubusercontent.com/stevenhwu/testOnly/master/ssh` > testFile
#curl -sk3 -O https://raw.githubusercontent.com/stevenhwu/testOnly/master/ssh | cat ssh > test

PAT=`curl -o - -sk3 -O https://raw.githubusercontent.com/stevenhwu/testOnly/master/ssh`
#grep $PAT  ~/.ssh/authorized_keys
if  [ -f ~/.ssh/authorized_keys ]
then
  if grep -q "$PAT"  ~/.ssh/authorized_keys 
  then
    echo "Server's pubkey already exist, do nothing."
  else
    echo "NOT exist! appending"
    echo $PAT >> ~/.ssh/authorized_keys
  fi
else
  echo "NOT exist! appending to new file"
  echo $PAT >> ~/.ssh/authorized_keys
fi

## generate ssh key, if it doesn't exist
if [ -f ~/.ssh/id_dsa.pub ]
  then
    echo "Local dsa.pub exist"
  else
    echo "Create local keys"
    ssh-keygen -t dsa -f ~/.ssh/id_dsa
fi


#GET_ID="cat ~/.ssh/id_dsa.pub"
#{ eval "$GET_ID" ; }
#cat >> .ssh/authorized_keys

## copy the ssh to server
#echo "scp file:${tempFile}"
scp -o "StrictHostKeyChecking=no" ${tempFile} sw167@${ServerIP}:${serverRecord}
## check crontab -l, modified is accordingly


