#!/bin/bash
## use sftp to reverse mirror materials server to each room
#echo ${MapRoomToIP[@]}
for r in "${!MapRoomToIP[@]}";
  do
  printf "sftp from localMirror to %s\tIP: %s\n" "$r" "${MapRoomToIP[$r]}";
  RoomSFTP="sftp://nescent@${MapRoomToIP[$r]}:/Users/nescent/Desktop/evo14/${r}";
  LocalMirror="${LocalServer}/${r}/";
  lftp -c "set sftp:connect-program 'ssh -a -x'; mirror -v -R --use-pget-n=5 --parallel=5  $LocalMirror $RoomSFTP;";
done;

