#!/bin/bash

if [ ! -n "${1}" ]
then
  today=`date +%d`
  today=`date -d 20140622 +%d`
else
  today=`date -d ${1} +%d`
fi

#echo $today
#echo ${MapDateToCode[$today]}
#echo ${MapDateToCode[22]}
## end testing

dateCode="${MapDateToCode[${today}]}"
oldDateCode=`expr $dateCode - 1`
#oldDateCode=`echo "$dateCode-1" | bc`

echo -e "Preprocess files at local Server. Day ${dateCode}.\n";

#### post process into ROOM folder

#for f in `ls ${LocalServerCache}/P*`;
#  do
#  id=`echo $f | sed 's/.*_\(.*\)\..*/\1/'`
#  session=${mapIDToSession[$id]}
#  room=`echo $session | sed 's/.*_\(.*\)/\1/'`
#  if `echo $session | grep -Eq "${dateCode}._.+"`
#  then 
    
 #   echo "$room $f $id  $session $room"
#    if [ ! -d "${LocalServer}/${room}/${session}" ]   
#    then   
#      mkdir -p ${LocalServer}/${room}/${session};   
#    fi
    #echo "first link $f"
#    ln -fs $f ${LocalServer}/${room}/${session}/ 
#  else 
#    echo "$session"
#  fi


#  ln -fs $f ${LocalServer}/${room}/${session}/
#done


for sess in `ls ${LocalServerCache}/bysess/`;
  do
  matchRoom=`echo $sess | sed 's/.*_\(.*\)/\1/'`
  for talk in `ls ${LocalServerCache}/bysess/$sess/P*`
    do 
    id=`echo $talk | sed 's/.*_\(.*\)\..*/\1/'`
    session=${mapIDToSession[$id]}
    room=`echo $session | sed 's/.*_\(.*\)/\1/'`    
    day=`echo $session | sed 's/\([01234]\)._.*/\1/'`
    dayString=${MapDayCodeToDayString[$day]}
    destFolder=${LocalServer}/${room}/${dayString}/${session}/
    if [ "$matchRoom" == "$room"  ] 
    then 
    #  echo "ln -s $sess $day $matchRoom $talk $talkRoom  "
      
      if [ ! -d $destFolder ]
      then
        mkdir -p $destFolder;
      fi
      ln -fs $talk $destFolder 
    else
      echo "ERROR!!! ========= $sess $matchRoom $talk $talkRoom"
    fi
  done
done



for r in "${!MapRoomToIP[@]}"; 
  do 
#    if [ ! -d "${LocalServer}/${r}" ] 
#    then 
#      mkdir -p ${LocalServer}/$r; 
#    fi 
 
  #echo -e "=====Run ${dateCode}*_${r}=====${oldDateCode}=====\n\n" 
  removeOld=`ls ${LocalServer}/${r}/ | grep -E "${oldDateCode}._"` 
#  echo "${LocalServer}/${r}"
#  echo `ls  ${LocalServer}/${r}`
#  echo "remove: $removeOld"
  for old in ${removeOld}; do  
#    rm -r ${LocalServer}/${r}/${old}/; 
    echo "Remov this ${LocalServer}/${r}/${old}/"
  done 


#  rsync -arz --delete ${LocalServerCache}/${r} ${LocalServer}/${r};  

#  rsync -arzivvv --progress  --include "*${dateCode}*_${r}*" --exclude "*" --delete-excluded ${LocalServerCache}/ ${LocalServer}/${r}; 
#  rsync -arzivvv --progress  --include "${dateCode}*_${r}" --exclude "${oldDateCode}*" --delete-excluded ${LocalServerCache}/ ${LocalServer}/${r}/; 
done 
