#!/bin/bash
## rsync from materials server to each room
#echo ${MapRoomToIP[@]}


if [ ! -n "${1}" ]
  then
    RoomList="${!MapRoomToIP[@]}"
  else
    RoomList=$1
fi

for r in $RoomList;
do
  printf "rsync from localMirror to %s\tIP: %s\n" "$r" "${MapRoomToIP[$r]}";
  Room="admin@${MapRoomToIP[$r]}:/Users/admin/Desktop/${r}/";
  LocalMirror="${LocalServer}/${r}/";
  rsync -azL --delete ${LocalMirror} ${Room};
done;


