#!/bin/bash

echo -e "Preprocess manually uploaded files at local Server";
LocalServerManualUpload=${LocalServer}/ManualUpload/
evoServerName=`hostname` 
#### sync manually uploaded files between primary and secondary server
if [  "$evoServerName" == "evo-primary" ]
    then 
    echo "sync manually uploaded files between primary and secondary servers"
    otherIP=${evoSecondaryIP}
elif [  "$evoServerName" == "evo-secondary" ]
    then
    otherIP=${evoPrimaryIP}
fi
echo $otherIP


if [  -n $otherIP ]
then
    rsync -e 'ssh' -az ${LocalServerManualUpload} evo14@${otherIP}:${LocalServerManualUpload}
    rsync -e 'ssh' -az evo14@${otherIP}:${LocalServerManualUpload} ${LocalServerManualUpload}
else
    echo "Warning!! Running on other server other then evo-* server"
fi


#### Preprocess manually uploaded files at local Server

for talkname in `ls ${LocalServerManualUpload}`;
#for talk in `find ${LocalServerManualUpload} -name P*_*`
do
  talk=${LocalServerManualUpload}/${talkname}
  echo "==$talk"
  if [ -d $talk ]
  then 
#    echo "link inside folders"
    id=${talkname}

    session=${mapIDToSession[$id]}
    room=`echo $session | sed 's/.*_\(.*\)/\1/'`
    dayCode=`echo $session | sed 's/\([01234]\)._.*/\1/'`
    dayString=${MapDayCodeToDayString[$dayCode]}
    destFolder=${LocalServer}/${room}/${dayString}/${session}/
    if [ ! -d $destFolder ]
    then
      mkdir -p $destFolder;
    fi
 
    for fileInFolder in `ls $talk`
    do     
      echo "ln -fs ${talk}/${fileInFolder} $destFolder"
      ln -fs ${talk}/${fileInFolder} $destFolder
    done
  else
#    echo "linkFiles"
    id=`echo $talk | sed 's/.*_\(.*\)\..*/\1/'`

    session=${mapIDToSession[$id]}
    room=`echo $session | sed 's/.*_\(.*\)/\1/'`    
    dayCode=`echo $session | sed 's/\([01234]\)._.*/\1/'`
    dayString=${MapDayCodeToDayString[$dayCode]}
    destFolder=${LocalServer}/${room}/${dayString}/${session}/

    echo "$id $session $room $dayCode $dayString $talk"
    if [ ! -d $destFolder ]
    then
      mkdir -p $destFolder;
    fi
    echo "ln -fs $talk $destFolder"
    ln -fs $talk $destFolder 

 fi

done


BrokenLinks=`find ${LocalServer} -type l -xtype l`
for blink in ${BrokenLinks}
do
    echo "Warning!! broken links will be removed: ${blink}"
    rm ${blink}
done

