#!/bin/bash
## rsync from materials server to each room
#Two parameters, Room and Day

if [[ ! -n "${1}" || ${1} == "ALL" ||  ${1} == "all" ]]
then
  RoomList="${!MapRoomToIP[@]}"
  echo -e "Sync from Local to ALL Rooms: ${RoomList}."
else
  RoomList=$1
  echo -e "Sync from Local to Room ${RoomList} ONLY."
fi

if [ ! -n "${2}" ]
then
  today=`date +%d`
  allDateCode="${MapDateToCode[${today}]}"
elif [[ ${2} == "ALL" ||  ${2} == "all" ]]
  then
  allDateCode="0 1 2 3 4"
else
  allDateCode=${2}
fi

#echo $today ${MapDateToCode[$today]} ${MapDayCodeToDayString[$dayCode]}
#oldDateCode=`expr $dateCode - 1`
#oldDateCode=`echo "$dateCode-1" | bc`

for dateCode in $allDateCode
do
  dayString=${MapDayCodeToDayString[$dateCode]}
  echo -e "Sync for Day ${dateCode} ${dayString}.";
 
  for r in $RoomList;
  do
    printf "rsync from localMirror to %s\tIP: %s\n" "$r" "${MapRoomToIP[$r]}";
    Room="admin@${MapRoomToIP[$r]}:/Users/admin/Desktop/${r}/${dayString}/";
    LocalMirror="${LocalServer}/${r}/${dayString}/";
    rsync -e 'ssh -o StrictHostKeyChecking=no' -azL --delete ${LocalMirror} ${Room};
  #   --update --delete
  done;
  
done
