#!/bin/bash
## use sftp to reverse mirror materials server to each room
#echo ${MapRoomToIP[@]}


if [ ! -n "${1}" ]
  then
    RoomList="${!MapRoomToIP[@]}"
  else
    RoomList=$1
fi

for r in $RoomList;
  do
  printf "sftp from localMirror to %s\tIP: %s\n" "$r" "${MapRoomToIP[$r]}";
  RoomSFTP="sftp://admin@${MapRoomToIP[$r]}:/Users/admin/Desktop/${r}";
  LocalMirror="${LocalServer}/${r}/";
  lftp -c "set sftp:connect-program 'ssh -a -x'; mirror -v -R -L --parallel=3  $LocalMirror $RoomSFTP;";
done;

