#!/bin/bash

if [  -n "${1}" ]
then
  for id in $@
  do
    pat="*_${id}.*"
    list=`find ${LocalServer} -name ${pat}`
    out="`echo $list | sed 's/\s/\n/g'`"
    echo -e  "$out\n================"
  done
else 
  echo "error! no ID"
fi 

