#!/bin/bash
## Map room number to IP address
declare -Ax MapRoomToIP
MapRoomToIP=(
#["BalC"]=""
#["201"]=""
#["205"]=""
#["206"]=""
#["301A"]="152.3.59.2"
["301B"]="192.168.1.135"
#["302A"]="10.0.5.64"
#["302B"]=""
#["302C"]=""
#["303"]=""
#["304"]=""
#["305A"]=""
#["305B"]=""
#["306A"]=""
#["306B"]=""
#["306C"]=""
#["307"]=""

)
export MapRoomToIP

## Map date to folder code
declare -x MapDateToCode
MapDateToCode=(
[20]=0
[21]=1
[22]=2
[23]=3
[24]=4
)
export MapDateToCode
echo "Exporting mapping"
