#!/bin/bash
## Map room number to IP address
declare -Ax MapRoomToIP
MapRoomToIP=(
["201"]="10.12.99.1"
###["205"]="10.12.99.2"
["206"]="10.12.99.3"
["301A"]="10.12.99.4"
["301B"]="10.12.99.5"
["302A"]="10.12.99.6"
["302B"]="10.12.99.7"
["302C"]="10.12.99.8"
["303"]="10.12.99.9"
["304"]="10.12.99.10"
["305A"]="10.12.99.11"
["305B"]="10.12.99.12"
["306A"]="10.12.99.13"
["306B"]="10.12.99.14"
["306C"]="10.12.99.15"
###["307"]="10.12.99.16"
["402"]="10.12.99.17"
["BalC"]="10.12.99.18"
)
export MapRoomToIP

defaultFolder="/Users/admin/Desktop/${1}/"
function sshRoom (){
defaultFolder="/Users/admin/Desktop/${1}/"
#echo $defaultFolder;
ssh admin@${MapRoomToIP[$1]} -t "cd $defaultFolder; echo \`pwd\`; bash --login;";
} 
export -f sshRoom

allRoomList=${!MapRoomToIP[@]}
export allRoomList

## Map date to folder code
declare -x MapDateToCode
MapDateToCode=(
[20]=0
[21]=1
[22]=2
[23]=3
[24]=4
)
export MapDateToCode

declare -x MapDayCodeToDayString
MapDayCodeToDayString=(
[0]="FRI"
[1]="SAT"
[2]="SUN"
[3]="MON"
[4]="TUE"
[20]="FRI"
[21]="SAT"
[22]="SUN"
[23]="MON"
[24]="TUE"




)
export MapDayCodeToDayString

