#!/bin/bash
## don't think this works for mac hostname -I
ServerIP="192.168.1.199"
serverRecord="/home/sw167/Desktop/Evo14LocalMirror/EvoPresentation/RoomInfo/"
Room=$1

tempFile="/Users/nescent/Desktop/evo14/${1}_info"

if [ -n "${1}" ]
  then 
  echo "!!Room:${1}"
else
  echo "Please provide room code!! Exit script"
  return 6
fi
# One of these should work
ifconfig | grep 'inet ' | cut -d: -f2 | awk '{ print $2}' > ${tempFile}
ifconfig wlp3s0| grep 'inet ' | cut -d: -f2 | awk '{ print $2}'
ifconfig | awk -F ":"  '/inet /{split($1,a," ");print a[2]}'
ifconfig | awk -F ' *|:' '/inet /{print $2}'
#if not, go back to the old way
ifconfig

## send IP to server


## add pub key to authorized_keys
cat `curl -sk3 -O https://raw.githubusercontent.com/stevenhwu/testOnly/master/ssh` > testFile




## generate ssh key, if it doesn't exist
if [ -f ~/.ssh/id_dsa.pub ]
  then
    echo "dsa.pub exist"
  else
    ssh-keygen -t dsa -f ~/.ssh/id_dsa
fi


GET_ID="cat ~/.ssh/id_dsa.pub"
{ eval "$GET_ID" ; }
 cat >> .ssh/authorized_keys

## copy the ssh to server
echo "scp file:${tempFile}"
scp ${tempFile} sw167@${ServerIP}:${serverRecord}
## check crontab -l, modified is accordingly



